config/routes.rb
Rails.application.routes.draw do
  root 'airlines#index'

  resources :airlines, only: [:new, :index, :show, :create]
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :airlines, only: [:index, :show] do
        resources :reviews, only: [:create, :show]
      end
    end
  end
end

app/models/airline.rb
class Airline < ApplicationRecord
  validates :name, presence: true
  validates :destinations, presence: true
  validates :overall_rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5, message: "must be between 1 - 5"}

  has_many :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :description, presence: true
  validates :price_rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5, message: "must be between 1 - 5"}
  validates :service_rating, presence: true,  numericality: { only_integer: true }, inclusion: { in: 1..5, message: "must be between 1 - 5"}
  validates :reliability_rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5, message: "must be between 1 - 5"}
  validates :overall_rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 1..5, message: "must be between 1 - 5"}

  belongs_to :airline
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :profile_photo, ProfilePhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :encrypted_password, presence: true
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :reviews
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController

  def index
    @airlines = Airline.all
  end

  def new
    @airline = Airline.new
  end

  def create
    @airline = Airline.new(airline_params)
    if @airline.save
      flash[:notice] = "Airline added successfully"
      redirect_to airline_path(@airline)
    else
      flash[:error] = @airline.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
  end



private

 def airline_params
  params.require(:airline).permit(:name, :destinations, :overall_rating)
 end
end

app/controllers/api/v1/airlines_controller.rb
class Api::V1::AirlinesController < ApplicationController


  def index
    render json: Airline.all
  end

  def show
    @airline = Airline.find(params[:id])

    render json: { airline: @airline, reviews: @airline.reviews }
  end

#   def create
#   data = JSON.parse(request.body.read)
#   new_game = Airline.create(name: data["name"], destinations: data["promo_image_url"], overall_rating: 1 )
#   render json: new_airline
# end


  def airline_params
    params.require(:airline).permit(:name, :destinations, :overall_rating)
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
   before_action :authorize_user, except: :show

  def create
    new_review = Review.new(review_params)
    new_review.user = current_user
    new_review.airline_id = params["review"]["airline_id"]
    if new_review.save
      render json: new_review
    else
      render json: {error: new_review.errors.full_messages}
    end
  end

  def show
    render json: Review.find(params[:id])
  end

  def destroy
    if current_user_access
      Review.destroy(params[:id])
    else
      render json: {message: "You can only delete your own reviews."}, status: 401
    end
  end

  private

  def review_params
    params.permit(:description, :price_rating, :service_rating, :reliability_rating, :overall_rating, :airline_id)
  end

  def authorize_user
    if !user_signed_in?
      render json: {message: "You must be signed in to create a review."}

    end
  end

  def current_user_access
    current_user.id == Review.find(params[:id]).user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_photo])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/airlines/index.html.erb
<ul>
<div class="row">
  <div class="large-12 columns">
    <h1 class="tag-line"> Where Jet Setters Talk</h1>
    <ul class="flex-container">
    <% @airlines.each do |airline| %>
      <li class="airline_box">
      <%= link_to airline.name, airline_path(airline) %>
      <img src="<%= airline.image_logo %>">
      Jet Setters say:
      <%=airline.overall_rating%><i class="fas fa-star"></i>
      </li>
    <% end %>
    </ul>

  </div>
</div>
<h5><%= link_to "Add New Airline", new_airline_path %></h5>
</ul>

app/views/airlines/new.html.erb
<%= form_for @airline, html: {class: "new_airline", id: "new_airline"} do |f| %>
  <% if @airline.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@airline.errors.count, "error") %> prohibited this airline from being saved:</h2>
	    <ul>
	      <% @airline.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>
<div class="row">
  <div class="small-6 large-6 columns">
    <div class="panel callout radius">
      <h3>Your favorite Airline not here? </h3>
      <h4>Just add it</h4>
        <div class='row'>
          <%= f.label :name, 'Airline Name' %>
          <%= f.text_field :name%>
        </div>
        <div class='row'>
          <%= f.label :destinations %>
          <%= f.text_field :destinations %>
        </div>
        <div class='row'>
          <%= f.label :overall_rating %>
          <%= f.text_field :overall_rating%>
        </div>
        <div class="submit">
          <%= f.submit "Add Airline" %>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/airlines/show.html.erb
<div id="app" ></div>

app/views/homes/index.html.erb
<div id="app" ></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AiReview</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Marvel" rel="stylesheet">
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1 class="AiReview"><a href="/"><i class="fas fa-plane"></i> AiReview</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li class="active"><img src="<%= current_user.profile_photo %>" width="45" height="45" /></li>
          <li class="active"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li class="active"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="active"><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>